import { randomBytes, timingSafeEqual } from "node:crypto";
import type { Prisma, PrismaClient } from "@sla/db";
import { ZendeskApiError, ZendeskClient } from "./client";
import type { ZendeskOAuthConfig } from "./oauth";
import {
  mapAuditToRawEvent,
  mapTicketDeletedToRawEvent,
  mapTicketToRawEvent,
  mapUserToRawEvent,
  type RawEventInput,
} from "./rawEvents";
import { loadFreshZendeskCredentials, refreshAfterUnauthorized } from "./tokenLifecycle";

/** Random per-integration secret, generated once at connect and never rotated on reconnect (see Integration.webhookSecret's doc comment). */
export function generateWebhookSecret(): string {
  return randomBytes(24).toString("hex");
}

/**
 * Zendesk's own webhook signing secret can't be used here: it's generated by
 * Zendesk *after* a webhook is created, with no field anywhere in the
 * creation form to hand Zendesk one of our own choosing — so HMAC request
 * signing (which needs a secret both sides agree on in advance) isn't
 * actually available to us. What the creation form's Authentication dropdown
 * does offer is "Bearer token", where the customer pastes a token of their
 * choice and Zendesk sends it back as `Authorization: Bearer <token>` on
 * every call. Verification here is a constant-time compare against that
 * header, using this integration's `webhookSecret` as the token. (Jira
 * does let the customer set the secret, so it verifies an HMAC signature
 * instead — see `verifyJiraWebhookSignature`.)
 */
export function verifyZendeskWebhookSecret(expected: string, authorizationHeader: string | null): boolean {
  const match = authorizationHeader ? /^Bearer (.+)$/.exec(authorizationHeader) : null;
  const provided = match?.[1];
  if (!provided) return false;

  const expectedBuffer = Buffer.from(expected);
  const providedBuffer = Buffer.from(provided);
  // timingSafeEqual throws on mismatched lengths rather than returning false.
  if (expectedBuffer.length !== providedBuffer.length) return false;
  return timingSafeEqual(expectedBuffer, providedBuffer);
}

/**
 * The webhook payload shape is whatever the customer's Zendesk trigger/event
 * subscription is configured to send, not a shape we control — this reads a
 * ticket id leniently from the handful of shapes Zendesk's admin UI actually
 * offers: a custom trigger body of `{"ticket_id": "{{ticket.id}}"}` (what the
 * settings page instructs customers to configure), or a native "Ticket
 * Events" subscription's `{"detail": {"id": ...}, ...}"` / `{"ticket": {...}}`
 * envelope.
 */
export function extractZendeskWebhookTicketId(payload: unknown): number | null {
  if (payload === null || typeof payload !== "object") return null;
  const body = payload as Record<string, unknown>;
  const ticket = body.ticket as Record<string, unknown> | undefined;
  const detail = body.detail as Record<string, unknown> | undefined;
  const candidate = body.ticket_id ?? ticket?.id ?? detail?.id ?? body.id;
  const id = typeof candidate === "string" ? Number(candidate) : candidate;
  return typeof id === "number" && Number.isInteger(id) && id > 0 ? id : null;
}

/**
 * Cheap replay mitigation (roadmap step 30) alongside `verifyZendeskWebhookSecret`
 * above: a captured request — secret included — replayed later is rejected
 * once its payload's timestamp has aged out. Zendesk's own webhook signing
 * headers (`X-Zendesk-Webhook-Signature-Timestamp`) aren't usable here for
 * the same reason its signing secret isn't (see this file's top comment) —
 * that header is tied to the "Signing Secret" authentication method, not the
 * Bearer-token one this integration uses. Instead, the documented custom
 * trigger body (see the settings page) now includes a `timestamp` field
 * populated from the `{{ticket.updated_at}}` placeholder; a native "Ticket
 * Events" envelope's `detail`/`ticket` shapes are also checked leniently,
 * mirroring `extractZendeskWebhookTicketId`'s own fallbacks.
 *
 * The trigger body must use `{{ticket.updated_at_with_timestamp}}`, which
 * Zendesk's placeholder reference documents as ISO-8601 in UTC at minute
 * precision (`2013-12-12T05:35Z`). Plain `{{ticket.updated_at}}` renders only a
 * date ("May 18", with no year in the current year), which `Date.parse` reads
 * as a date in 2001. So strings are accepted only when they start with an
 * ISO `YYYY-MM-DD` date, never parsed loosely. Raw epoch numbers are still
 * accepted. The minute truncation makes a fresh delivery look up to 60s old,
 * well inside the 5-minute window.
 */
export function extractZendeskWebhookTimestamp(payload: unknown): number | null {
  if (payload === null || typeof payload !== "object") return null;
  const body = payload as Record<string, unknown>;
  const ticket = body.ticket as Record<string, unknown> | undefined;
  const detail = body.detail as Record<string, unknown> | undefined;
  const candidate = body.timestamp ?? body.time ?? ticket?.updated_at ?? detail?.updated_at ?? body.updated_at;

  if (typeof candidate === "number" && Number.isFinite(candidate)) {
    // Below this threshold a value can only be epoch seconds, never milliseconds.
    return candidate < 1e12 ? candidate * 1000 : candidate;
  }
  if (typeof candidate === "string") {
    if (!/^\d{4}-\d{2}-\d{2}/.test(candidate.trim())) return null;
    const parsed = Date.parse(candidate.trim());
    return Number.isNaN(parsed) ? null : parsed;
  }
  return null;
}

/** Missing or unparseable timestamps count as stale — fail closed, matching `verifyZendeskWebhookSecret`'s own default-deny shape. */
export function isZendeskWebhookTimestampFresh(payload: unknown, now: number = Date.now(), maxAgeMs = 5 * 60_000): boolean {
  const timestamp = extractZendeskWebhookTimestamp(payload);
  if (timestamp === null) return false;
  return Math.abs(now - timestamp) <= maxAgeMs;
}

export interface WebhookIngestResult {
  ticketsFetched: number;
  ticketAuditsFetched: number;
  /**
   * True when this call found the ticket gone (deleted, merged away). The
   * deletion is recorded as a raw event instead of the ticket; normalizing
   * this ticket afterwards soft-deletes its Case.
   */
  ticketDeleted?: boolean;
}

/**
 * Targeted refetch of one ticket, triggered by an inbound webhook (roadmap
 * step 20) rather than the incremental export the two-speed poller uses.
 * Deliberately never touches Integration.cursor: that watermark belongs to
 * the incremental-export stream `runZendeskBackfill` advances, and a
 * single-ticket refetch must not perturb it. Writes land through the same
 * RawEvent mapping functions the poller uses, so the next
 * normalization pass — poll-driven or webhook-driven — picks
 * them up identically either way.
 */
export async function runZendeskWebhookIngest(
  prisma: PrismaClient,
  integrationId: string,
  config: ZendeskOAuthConfig,
  ticketId: number,
): Promise<WebhookIngestResult> {
  const credentials = await loadFreshZendeskCredentials(prisma, integrationId, config);
  const client = new ZendeskClient(credentials, {
    onUnauthorized: (failed) => refreshAfterUnauthorized(prisma, integrationId, config, failed),
  });

  let ticket;
  let users;
  try {
    ({ ticket, users } = await client.fetchTicket(ticketId));
  } catch (error) {
    if (error instanceof ZendeskApiError && error.status === 404) {
      const deletion = mapTicketDeletedToRawEvent(ticketId);
      await prisma.rawEvent.createMany({
        data: [
          {
            integrationId,
            providerEventId: deletion.providerEventId,
            sourceHash: deletion.sourceHash,
            payload: deletion.payload as Prisma.InputJsonValue,
          },
        ],
        skipDuplicates: true,
      });
      return { ticketsFetched: 0, ticketAuditsFetched: 0, ticketDeleted: true };
    }
    throw error;
  }
  const rawEvents: RawEventInput[] = [mapTicketToRawEvent(ticket, users)];

  let ticketAuditsFetched = 0;
  let nextPageUrl: string | undefined;
  for (;;) {
    const page = await client.fetchTicketAuditsPage(ticketId, nextPageUrl);
    rawEvents.push(...page.audits.map(mapAuditToRawEvent), ...(page.users ?? []).map(mapUserToRawEvent));
    ticketAuditsFetched += page.audits.length;
    if (!page.next_page) break;
    nextPageUrl = page.next_page;
  }

  await prisma.rawEvent.createMany({
    data: rawEvents.map((input) => ({
      integrationId,
      providerEventId: input.providerEventId,
      sourceHash: input.sourceHash,
      payload: input.payload as Prisma.InputJsonValue,
    })),
    skipDuplicates: true,
  });

  return { ticketsFetched: 1, ticketAuditsFetched };
}
