import { Actions } from "@/actions";
import { SlaAutoRefreshProvider } from "@/components/shared/SlaAutoRefreshProvider";
import { CaseListView } from "../csr/list-view";

export const CaseList = async () => {
  const data = await Actions.Cases.getList();
  const worker = await Actions.WorkerSettings.getData();

  return (
    <>
      <CaseListView
        data={{
          asOf: "2026-09-26T12:51:05.013Z",
          cases: [
            {
              caseId: "cmugf53og00crryry8xqqjj4i",
              externalId: "47",
              subject: "hi https",
              customerName: "SLA-DMEO",
              requesterName: "Yasser Alnajjar",
              priority: "at_risk",
              tier: null,
              channel: "web",
              openedAt: "2026-09-24T19:21:57.000Z",
              closedAt: "2026-09-24T19:49:29.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: {
                system: "jira",
                externalId: "SCRUM-12",
                confidence: "certain",
                statusName: null,
              },
              liveCommitment: null,
              settledCommitment: {
                kind: "first_response",
                status: "met",
                targetMinutes: 30,
                elapsedSeconds: 277,
                supportLegMinutes: 503,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53oa00cjryryd1x0a3xf",
              externalId: "46",
              subject: "Test new design-2",
              customerName: "SLA-DMEO",
              requesterName: "Yasser Alnajjar",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-23T18:12:17.000Z",
              closedAt: "2026-09-23T18:20:09.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: {
                system: "jira",
                externalId: "SCRUM-11",
                confidence: "certain",
                statusName: null,
              },
              liveCommitment: null,
              settledCommitment: {
                kind: "first_response",
                status: "met",
                targetMinutes: 30,
                elapsedSeconds: 105,
                supportLegMinutes: 6,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53o600cbryry6iq7820g",
              externalId: "45",
              subject: "Test new design",
              customerName: "Phase 4 Native Test",
              requesterName: "Romysaa",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-23T14:34:37.000Z",
              closedAt: "2026-09-23T18:11:44.000Z",
              worstCommitmentStatus: "breached",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: {
                system: "jira",
                externalId: "SCRUM-9",
                confidence: "certain",
                statusName: null,
              },
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "breached",
                targetMinutes: 60,
                elapsedSeconds: 12811,
                supportLegMinutes: 2228,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53o000c4ryrywp3oepri",
              externalId: "44",
              subject: "Test Ticket 10 hours #6",
              customerName: "Phase 4 Native Test",
              requesterName: "Romysaa",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-22T23:09:33.000Z",
              closedAt: "2026-09-22T23:19:18.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "met",
                targetMinutes: 60,
                elapsedSeconds: 585,
                supportLegMinutes: 10,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53nw00c1ryry78ywbi9y",
              externalId: "43",
              subject: "Phase 4 Native Test Ticket 10 hours #5",
              customerName: "Phase 4 Native Test",
              requesterName: "Romysaa",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-22T22:37:03.000Z",
              closedAt: "2026-09-22T23:19:22.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "met",
                targetMinutes: 60,
                elapsedSeconds: 2539,
                supportLegMinutes: 42,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53nh00brryryw84t0ukn",
              externalId: "42",
              subject: "Phase 4 Native Test Ticket 10 hours #4",
              customerName: "Phase 4 Native Test",
              requesterName: "Romysaa",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-22T09:54:14.000Z",
              closedAt: "2026-09-26T10:47:23.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "met",
                targetMinutes: 60,
                elapsedSeconds: 49,
                supportLegMinutes: 5813,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53nr00bxryrycf37tlpo",
              externalId: "41",
              subject: "Phase 4 Native Test Ticket 10 hours #4",
              customerName: "Phase 4 Native Test",
              requesterName: "Romysaa",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-22T09:52:43.000Z",
              closedAt: "2026-09-26T10:47:23.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "met",
                targetMinutes: 60,
                elapsedSeconds: 182,
                supportLegMinutes: 5815,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53n600bjryry16j1xroq",
              externalId: "40",
              subject: "Phase 4 Native Test Ticket 10 hours #3",
              customerName: "Phase 4 Native Test",
              requesterName: "Romysaa",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-22T09:50:27.000Z",
              closedAt: "2026-09-26T10:47:23.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "met",
                targetMinutes: 60,
                elapsedSeconds: 122,
                supportLegMinutes: 5817,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53n200bgryrykq8h5y98",
              externalId: "39",
              subject: "Phase 4 Native Test Ticket 10 hours #2",
              customerName: "Phase 4 Native Test",
              requesterName: "Romysaa",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-22T09:26:33.000Z",
              closedAt: "2026-09-26T09:46:26.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "met",
                targetMinutes: 60,
                elapsedSeconds: 1102,
                supportLegMinutes: 5780,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53mw00bdryry3yw1lmui",
              externalId: "38",
              subject: "Phase 4 Native Test Ticket 10 hours",
              customerName: "Phase 4 Native Test",
              requesterName: "Romysaa",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-22T09:23:03.000Z",
              closedAt: "2026-09-26T09:46:26.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "met",
                targetMinutes: 60,
                elapsedSeconds: 194,
                supportLegMinutes: 5783,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53nl00buryryiqgxf2p1",
              externalId: "37",
              subject: "Phase 4 Native Test Ticket-4",
              customerName: "Phase 4 Native Test",
              requesterName: "Romysaa",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-22T09:02:32.000Z",
              closedAt: "2026-09-26T10:47:23.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "met",
                targetMinutes: 60,
                elapsedSeconds: 3185,
                supportLegMinutes: 5865,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53mr00baryryp6pbs866",
              externalId: "36",
              subject: "Phase 4 Native Test Ticket-3",
              customerName: "Phase 4 Native Test",
              requesterName: "Romysaa",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-22T09:01:04.000Z",
              closedAt: "2026-09-26T09:46:26.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "met",
                targetMinutes: 60,
                elapsedSeconds: 17,
                supportLegMinutes: 5805,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53mn00b7ryryb6j1p71f",
              externalId: "35",
              subject: "Phase 4 Native Test Ticket-2",
              customerName: "Phase 4 Native Test",
              requesterName: "Romysaa",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-22T08:59:37.000Z",
              closedAt: "2026-09-26T09:46:26.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "met",
                targetMinutes: 60,
                elapsedSeconds: 58,
                supportLegMinutes: 5807,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53mi00b4ryry9bvre3r1",
              externalId: "34",
              subject: "Phase 4 Native Test Ticket-2",
              customerName: "SLA-DMEO",
              requesterName: "D-Yasser Alnajjar",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-22T08:58:59.000Z",
              closedAt: "2026-09-26T09:46:26.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "met",
                targetMinutes: 60,
                elapsedSeconds: 26,
                supportLegMinutes: 5807,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53mc00b0ryry8sjcekag",
              externalId: "33",
              subject: "Phase 4 Native Test Ticket",
              customerName: "Phase 4 Native Test",
              requesterName: "Romysaa",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-22T08:50:16.000Z",
              closedAt: "2026-09-26T09:46:26.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "met",
                targetMinutes: 60,
                elapsedSeconds: 512,
                supportLegMinutes: 5816,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53nb00bmryrydc3e6809",
              externalId: "32",
              subject: "SLA First Response 30m (2)",
              customerName: "SLA-DMEO",
              requesterName: "Yasser Alnajjar",
              priority: "urgent",
              tier: null,
              channel: "web",
              openedAt: "2026-09-22T07:51:22.000Z",
              closedAt: "2026-09-26T10:47:23.000Z",
              worstCommitmentStatus: "breached",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "breached",
                targetMinutes: 20,
                elapsedSeconds: 7426,
                supportLegMinutes: 5936,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53m500awryry9bm995fh",
              externalId: "31",
              subject: "SLA First Response 30m",
              customerName: "SLA-DMEO",
              requesterName: "D-Yasser Alnajjar",
              priority: "urgent",
              tier: null,
              channel: "web",
              openedAt: "2026-09-22T07:50:06.000Z",
              closedAt: "2026-09-26T08:44:46.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "met",
                targetMinutes: 20,
                elapsedSeconds: 51,
                supportLegMinutes: 5815,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53l400a4ryryb19w2tno",
              externalId: "30",
              subject: "hi-2",
              customerName: "SLA-DMEO",
              requesterName: "D-Yasser Alnajjar",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-21T21:59:48.000Z",
              closedAt: "2026-09-25T22:35:26.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "met",
                targetMinutes: 60,
                elapsedSeconds: 876,
                supportLegMinutes: 5796,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53li00agryryu89l22lt",
              externalId: "29",
              subject: "hi",
              customerName: "SLA-DMEO",
              requesterName: "Yasser Alnajjar",
              priority: "high",
              tier: null,
              channel: "web",
              openedAt: "2026-09-21T21:58:16.000Z",
              closedAt: "2026-09-26T08:44:45.000Z",
              worstCommitmentStatus: "breached",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "breached",
                targetMinutes: 40,
                elapsedSeconds: 35294,
                supportLegMinutes: 6406,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53lb00a8ryry7lp8qqyq",
              externalId: "28",
              subject: "Test Assignee",
              customerName: null,
              requesterName: "Agent-2",
              priority: "urgent",
              tier: null,
              channel: "web",
              openedAt: "2026-09-21T21:53:15.000Z",
              closedAt: "2026-09-25T22:35:26.000Z",
              worstCommitmentStatus: "breached",
              assigneeName: "Jira Integration",
              primaryLink: {
                system: "jira",
                externalId: "SCRUM-8",
                confidence: "certain",
                statusName: null,
              },
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "breached",
                targetMinutes: 20,
                elapsedSeconds: 1300,
                supportLegMinutes: 4673,
                engineeringLegMinutes: 1129,
              },
            },
            {
              caseId: "cmugf53kv009uryryn7bfqr1x",
              externalId: "27",
              subject:
                "Ticket creation → The agent resolves it directly without a customer reply.",
              customerName: "SLA-DMEO",
              requesterName: "Yasser Alnajjar",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-21T20:59:09.000Z",
              closedAt: "2026-09-25T21:34:34.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: {
                system: "jira",
                externalId: "SCRUM-7",
                confidence: "certain",
                statusName: null,
              },
              liveCommitment: null,
              settledCommitment: {
                kind: "first_response",
                status: "met",
                targetMinutes: 30,
                elapsedSeconds: 143,
                supportLegMinutes: 4727,
                engineeringLegMinutes: 1068,
              },
            },
            {
              caseId: "cmugf53ko009oryry10md5cn4",
              externalId: "26",
              subject: "test error link ",
              customerName: "SLA-DMEO",
              requesterName: "Yasser Alnajjar",
              priority: "high",
              tier: null,
              channel: "web",
              openedAt: "2026-09-21T20:40:28.000Z",
              closedAt: "2026-09-25T21:34:34.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: {
                system: "jira",
                externalId: "SCRUM-6",
                confidence: "certain",
                statusName: null,
              },
              liveCommitment: null,
              settledCommitment: {
                kind: "first_response",
                status: "met",
                targetMinutes: 20,
                elapsedSeconds: 12,
                supportLegMinutes: 4746,
                engineeringLegMinutes: 1068,
              },
            },
            {
              caseId: "cmugf53kh009lryryp6h89pu4",
              externalId: "25",
              subject: "test-1",
              customerName: "SLA-DMEO",
              requesterName: "D-Yasser Alnajjar",
              priority: "high",
              tier: null,
              channel: "web",
              openedAt: "2026-09-21T20:27:38.000Z",
              closedAt: "2026-09-25T21:34:33.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: {
                system: "jira",
                externalId: "SCRUM-5",
                confidence: "certain",
                statusName: null,
              },
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "met",
                targetMinutes: 40,
                elapsedSeconds: 756,
                supportLegMinutes: 4759,
                engineeringLegMinutes: 1068,
              },
            },
            {
              caseId: "cmugf53lo00alryrywftjmsj8",
              externalId: "24",
              subject: "KAN-17 stale link repro test",
              customerName: "SLA-DMEO",
              requesterName: "D-Yasser Alnajjar",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-21T19:15:56.000Z",
              closedAt: "2026-09-26T08:44:46.000Z",
              worstCommitmentStatus: "breached",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "breached",
                targetMinutes: 60,
                elapsedSeconds: 45056,
                supportLegMinutes: 6569,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53lt00apryryzrt1r6xy",
              externalId: "23",
              subject: "ttttt",
              customerName: "SLA-DMEO",
              requesterName: "D-Yasser Alnajjar",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-21T18:38:43.000Z",
              closedAt: "2026-09-26T08:44:46.000Z",
              worstCommitmentStatus: "breached",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "breached",
                targetMinutes: 60,
                elapsedSeconds: 47306,
                supportLegMinutes: 6606,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53lz00atryrydr9i7q9n",
              externalId: "22",
              subject: "test at risk",
              customerName: "SLA-DMEO",
              requesterName: "D-Yasser Alnajjar",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-21T18:21:26.000Z",
              closedAt: "2026-09-26T08:44:46.000Z",
              worstCommitmentStatus: "breached",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "breached",
                targetMinutes: 60,
                elapsedSeconds: 48358,
                supportLegMinutes: 6623,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53k9009bryry6jkunjbj",
              externalId: "21",
              subject: "Unable to log in after password reset",
              customerName: "SLA-DMEO",
              requesterName: "Yasser Alnajjar",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-21T16:52:30.000Z",
              closedAt: "2026-09-25T17:31:26.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "first_response",
                status: "met",
                targetMinutes: 30,
                elapsedSeconds: 65,
                supportLegMinutes: 5798,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53k10094ryryqk9krmfo",
              externalId: "20",
              subject: "ticket phase 2",
              customerName: "SLA-DMEO",
              requesterName: "D-Yasser Alnajjar",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-21T14:59:14.000Z",
              closedAt: "2026-09-25T15:22:20.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "met",
                targetMinutes: 60,
                elapsedSeconds: 458,
                supportLegMinutes: 5782,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53js008wryry6yubez3p",
              externalId: "19",
              subject: "Test ticket with sla-2",
              customerName: "SLA-DMEO",
              requesterName: "D-Yasser Alnajjar",
              priority: "urgent",
              tier: null,
              channel: "web",
              openedAt: "2026-09-21T11:17:45.000Z",
              closedAt: "2026-09-25T12:51:37.000Z",
              worstCommitmentStatus: "breached",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "breached",
                targetMinutes: 20,
                elapsedSeconds: 2298,
                supportLegMinutes: 5854,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53jl008tryry28gjg6pq",
              externalId: "18",
              subject: "Test ticket with sla ",
              customerName: "SLA-DMEO",
              requesterName: "Yasser Alnajjar",
              priority: "urgent",
              tier: null,
              channel: "web",
              openedAt: "2026-09-21T11:15:08.000Z",
              closedAt: "2026-09-25T11:33:37.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "met",
                targetMinutes: 20,
                elapsedSeconds: 299,
                supportLegMinutes: 5778,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53j9008oryry3cdoqw3t",
              externalId: "17",
              subject: "ticket#1",
              customerName: "SLA-DMEO",
              requesterName: "Yasser Alnajjar",
              priority: "normal",
              tier: null,
              channel: "web",
              openedAt: "2026-09-21T10:57:42.000Z",
              closedAt: "2026-09-25T11:33:36.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "met",
                targetMinutes: 60,
                elapsedSeconds: 364,
                supportLegMinutes: 6,
                engineeringLegMinutes: 0,
              },
            },
            {
              caseId: "cmugf53o300c7ryrytwimpz0p",
              externalId: "1",
              subject: "SAMPLE: Unable to log in after password reset",
              customerName: null,
              requesterName: "Customer",
              priority: "low",
              tier: null,
              channel: "email",
              openedAt: "2026-09-19T10:41:21.000Z",
              closedAt: "2026-09-23T11:55:59.000Z",
              worstCommitmentStatus: "met",
              assigneeName: "D-Yasser Alnajjar",
              primaryLink: null,
              liveCommitment: null,
              settledCommitment: {
                kind: "resolution",
                status: "met",
                targetMinutes: 60,
                elapsedSeconds: 1372,
                supportLegMinutes: 5835,
                engineeringLegMinutes: 0,
              },
            },
          ],
        }}
        pollIntervalMs={worker.activePollIntervalMs}
      />
      {/* <SlaAutoRefreshProvider
        initInterval={worker.activePollIntervalMs - 2000}
      /> */}
    </>
  );
};
