const SECTIONS = [
  {
    title: "1. What we collect",
    body: [
      "When you connect an integration — Zendesk, Intercom, Jira, Linear, GitHub, or Slack — we read the data those systems' APIs return: tickets, issues, comments, status changes, timestamps, and related metadata needed to compute SLA commitments.",
      "We also collect account information you provide directly, such as your name, email address, and organization name, and standard technical data (IP address, browser, timestamps) generated by using the Service.",
    ],
  },
  {
    title: "2. What we don't collect",
    body: [
      "We never write to a connected system. No ticket, issue, field, tag, or comment in Zendesk, Jira, Linear, Intercom, or GitHub is ever created or modified by the Service. GitHub access is granted through a GitHub App with read-only permissions, installed only on the repositories you choose.",
    ],
  },
  {
    title: "3. How we use your data",
    body: [
      "We use the data read from your connected systems to derive customers, cases, and SLA commitments, to compute at-risk and breach status, and to send the Slack and email alerts you configure. We use account data to operate your account, provide support, and send service-related communications.",
      "We do not use your data to train machine learning models, and we do not sell your data to third parties.",
    ],
  },
  {
    title: "4. Data retention",
    body: [
      "Historical data is retained for 90 days from the date each integration is connected. This window is fixed and applies to the raw data returned by each connected system's API, the normalized events derived from it, and the customers, cases, and commitments computed from those events.",
      "If you disconnect an integration or close your account, data associated with it is deleted according to our standard retention schedule.",
    ],
  },
  {
    title: "5. Data sharing",
    body: [
      "We share data with subprocessors only as needed to operate the Service — for example, cloud hosting and email delivery providers — under contracts that require them to protect it. We do not share your data with third parties for their own marketing purposes.",
    ],
  },
  {
    title: "6. Security",
    body: [
      "We use industry-standard measures — encryption in transit, access controls, and least-privilege API scopes — to protect the data we hold. No system is perfectly secure, and we encourage you to use strong, unique credentials for any integration you connect.",
    ],
  },
  {
    title: "7. Your choices",
    body: [
      "You can disconnect any integration at any time from Settings, which stops new data from being read. You can request export or deletion of your account's data by contacting us.",
    ],
  },
  {
    title: "8. Changes to this policy",
    body: [
      "We may update this policy from time to time. Material changes will be communicated through the Service or by email before they take effect.",
    ],
  },
  {
    title: "9. Contact",
    body: [
      "Questions about this policy, or requests to access, export, or delete your data, can be sent to the contact address listed on our website.",
    ],
  },
];

export const PrivacyView = () => {
  return (
    <main className="flex-1">
      <section className="border-b border-border/60">
        <div className="mx-auto w-full max-w-3xl px-6 py-20 sm:py-24">
          <h1 className="font-display text-4xl font-medium tracking-tight sm:text-5xl">
            Privacy Policy
          </h1>
          <p className="mt-4 text-sm text-muted-foreground">
            Last updated September 27, 2026
          </p>
        </div>
      </section>

      <section className="py-16">
        <div className="mx-auto w-full max-w-3xl space-y-12 px-6">
          {SECTIONS.map((section) => (
            <div key={section.title} className="space-y-3">
              <h2 className="font-display text-xl font-medium tracking-tight">
                {section.title}
              </h2>
              {section.body.map((paragraph, i) => (
                <p key={i} className="leading-7 text-muted-foreground">
                  {paragraph}
                </p>
              ))}
            </div>
          ))}
        </div>
      </section>
    </main>
  );
};
