import { readdirSync, readFileSync, existsSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it, vi } from "vitest";

import robots from "../src/app/robots";
import sitemap from "../src/app/sitemap";
import { PUBLIC_PAGES } from "../src/lib/seo/pages";
import { classifyPath, robotsDisallowRules } from "../src/lib/seo/routes";
import { buildNoIndexHeaders, NOINDEX_PATH_PREFIXES } from "../seo-routes.mjs";

vi.mock("next-auth/jwt", () => ({ getToken: vi.fn(async () => null) }));

const APP_DIR = fileURLToPath(new URL("../src/app", import.meta.url));
const PRODUCTION_ORIGIN = "https://app.elapsedhq.io";

afterEach(() => {
  vi.unstubAllEnvs();
});

// ── The route tree, read from disk ──────────────────────────────────────────

interface RouteFile {
  kind: "page" | "handler";
  /** Real directory (route groups included), for walking up to the layouts. */
  dir: string;
  /** URL path with route groups removed and dynamic segments replaced by a sample value. */
  url: string;
}

function toUrl(dir: string): string {
  const segments = relative(APP_DIR, dir)
    .split(sep)
    .filter((segment) => segment && !/^\(.+\)$/.test(segment))
    .map((segment) => (segment.startsWith("[") ? "x" : segment));
  return `/${segments.join("/")}`;
}

function collectRoutes(dir: string): RouteFile[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return collectRoutes(path);
    if (entry.name === "page.tsx") return [{ kind: "page" as const, dir, url: toUrl(dir) }];
    if (/^route\.tsx?$/.test(entry.name)) return [{ kind: "handler" as const, dir, url: toUrl(dir) }];
    return [];
  });
}

const ROUTES = collectRoutes(APP_DIR);
const PAGES = ROUTES.filter((route) => route.kind === "page");
const HANDLERS = ROUTES.filter((route) => route.kind === "handler");

/** Static files generated by a route handler outside /api: public assets, not pages. */
const ASSET_ROUTES = ["/og-image.png"];

function sourcesFromRootTo(pageDir: string): string[] {
  const sources: string[] = [];
  for (let dir = pageDir; ; dir = dirname(dir)) {
    for (const file of ["layout.tsx", "page.tsx"]) {
      if (file === "page.tsx" && dir !== pageDir) continue;
      const path = join(dir, file);
      if (existsSync(path)) sources.push(readFileSync(path, "utf8"));
    }
    if (dir === APP_DIR) return sources;
  }
}

const DECLARES_NOINDEX = /noIndexMetadata\(|index:\s*false/;

describe("route classification", () => {
  it("finds the routes (guards the test itself against an empty walk)", () => {
    expect(PAGES.length).toBeGreaterThan(40);
    expect(HANDLERS.length).toBeGreaterThan(60);
  });

  it("classifies every page, so a new page cannot ship without a decision", () => {
    const unclassified = PAGES.filter((page) => classifyPath(page.url) === null).map((page) => page.url);
    expect(unclassified).toEqual([]);
  });

  it("classifies every route handler as API/internal, apart from the generated assets", () => {
    const stray = HANDLERS.filter((route) => !ASSET_ROUTES.includes(route.url))
      .filter((route) => classifyPath(route.url) !== "api")
      .map((route) => route.url);
    expect(stray).toEqual([]);
  });

  it("makes the public/indexable pages exactly the sitemap registry", () => {
    const indexable = PAGES.filter((page) => classifyPath(page.url) === "public-indexable").map((page) => page.url);
    expect([...indexable].sort()).toEqual(PUBLIC_PAGES.map((page) => page.path).sort());
  });

  it("covers the four classes with real routes", () => {
    const classes = new Set(PAGES.map((page) => classifyPath(page.url)));
    expect(classes).toEqual(new Set(["public-indexable", "public-noindex", "private"]));
    expect(classifyPath("/api/me")).toBe("api");
  });

  it.each([
    ["/", "public-indexable"],
    ["/docs/integrations/zendesk", "public-indexable"],
    ["/docs/deployment", "public-noindex"],
    ["/sign-in", "public-noindex"],
    ["/reset-password", "public-noindex"],
    ["/dashboard", "private"],
    ["/cases/abc", "private"],
    ["/settings/integrations/jira", "private"],
    ["/admin/tenants/x", "private"],
    ["/onboarding/activation", "private"],
    ["/api/integrations/slack/callback", "api"],
    ["/api/webhooks/jira/x", "api"],
    ["/docs/never-heard-of-it", null],
    ["/cases-studies", null],
  ])("classifies %s as %s", (path, expected) => {
    expect(classifyPath(path)).toBe(expected);
  });
});

describe("noindex coverage (inheritance)", () => {
  it("makes every non-indexable page declare noindex itself or through an ancestor layout", () => {
    const missing = PAGES.filter((page) => {
      const cls = classifyPath(page.url);
      return cls === "public-noindex" || cls === "private";
    })
      .filter((page) => !sourcesFromRootTo(page.dir).some((source) => DECLARES_NOINDEX.test(source)))
      .map((page) => page.url);
    expect(missing).toEqual([]);
  });

  it("never lets an indexable page inherit a noindex from a layout above it", () => {
    for (const route of PAGES.filter((page) => classifyPath(page.url) === "public-indexable")) {
      for (const source of sourcesFromRootTo(route.dir)) {
        expect(DECLARES_NOINDEX.test(source), route.url).toBe(false);
      }
    }
  });

  it("wires every indexable page to its own registry entry", () => {
    for (const route of PAGES.filter((page) => classifyPath(page.url) === "public-indexable")) {
      const source = readFileSync(join(route.dir, "page.tsx"), "utf8");
      expect(source, route.url).toContain(`getPageMetadata("${route.url}")`);
    }
  });
});

describe("X-Robots-Tag headers", () => {
  const headers = buildNoIndexHeaders();

  it("marks the API and every private prefix, both the bare path and everything below", () => {
    const sources = headers.map((rule) => rule.source);
    expect(sources).toContain("/api");
    expect(sources).toContain("/api/:path*");
    expect(sources).toContain("/dashboard");
    expect(sources).toContain("/dashboard/:path*");
    expect(sources).toHaveLength(NOINDEX_PATH_PREFIXES.length * 2);
    for (const rule of headers) {
      expect(rule.headers).toEqual([{ key: "X-Robots-Tag", value: "noindex, nofollow" }]);
    }
  });

  it("never covers a public page", () => {
    for (const page of PUBLIC_PAGES) {
      const covered = NOINDEX_PATH_PREFIXES.some(
        (prefix) => page.path === prefix || page.path.startsWith(`${prefix}/`),
      );
      expect(covered, page.path).toBe(false);
    }
  });
});

// ── robots.txt and sitemap.xml ──────────────────────────────────────────────

/** Google's matching: the longest matching pattern wins, and Allow wins a tie. `*` and a trailing `$` are supported. */
function isBlocked(
  rules: { allow: string[]; disallow: string[] },
  path: string,
): boolean {
  const matches = (pattern: string) => {
    const anchored = pattern.endsWith("$");
    const body = (anchored ? pattern.slice(0, -1) : pattern)
      .replace(/[.+?^${}()|[\]\\]/g, "\\$&")
      .replace(/\*/g, ".*");
    return new RegExp(`^${body}${anchored ? "$" : ""}`).test(path);
  };
  const longest = (patterns: string[]) =>
    Math.max(-1, ...patterns.filter(matches).map((pattern) => pattern.length));
  return longest(rules.disallow) > longest(rules.allow);
}

function productionRobots() {
  vi.stubEnv("NEXTAUTH_URL", PRODUCTION_ORIGIN);
  const result = robots();
  const rule = Array.isArray(result.rules) ? result.rules[0]! : result.rules;
  const list = (value: string | string[] | undefined) =>
    value === undefined ? [] : Array.isArray(value) ? value : [value];
  return {
    result,
    rules: { allow: list(rule.allow), disallow: list(rule.disallow) },
  };
}

describe("robots.txt", () => {
  it("points crawlers at the sitemap on the production origin", () => {
    const { result } = productionRobots();
    expect(result.sitemap).toBe(`${PRODUCTION_ORIGIN}/sitemap.xml`);
  });

  it("leaves every public page crawlable", () => {
    const { rules } = productionRobots();
    for (const page of PUBLIC_PAGES) {
      expect(isBlocked(rules, page.path), page.path).toBe(false);
    }
  });

  it("keeps the render-critical files and the SEO files crawlable", () => {
    const { rules } = productionRobots();
    for (const path of [
      "/_next/static/chunks/main.js",
      "/_next/static/css/app.css",
      "/_next/image",
      "/favicon.ico",
      "/icon.png",
      "/apple-icon.png",
      "/icon-512.png",
      "/og-image.png",
      "/manifest.webmanifest",
      "/sitemap.xml",
      "/robots.txt",
    ]) {
      expect(isBlocked(rules, path), path).toBe(false);
    }
  });

  it("keeps the sign-in, sign-up and forgot-password forms crawlable so their noindex tag is seen", () => {
    const { rules } = productionRobots();
    for (const path of ["/sign-in", "/sign-up", "/forgot-password", "/docs/deployment"]) {
      expect(isBlocked(rules, path), path).toBe(false);
    }
  });

  it("blocks the app, admin, API, OAuth callbacks, webhooks and token pages", () => {
    const { rules } = productionRobots();
    const blocked = [
      ...PAGES.filter((page) => ["private", "public-noindex"].includes(classifyPath(page.url) ?? ""))
        .map((page) => page.url)
        .filter((url) => NOINDEX_PATH_PREFIXES.some((prefix) => url === prefix || url.startsWith(`${prefix}/`))),
      ...HANDLERS.map((route) => route.url).filter((url) => url.startsWith("/api")),
      "/api/integrations/jira/callback",
      "/api/auth/callback/credentials",
      "/api/webhooks/zendesk/abc",
      "/api/health",
      "/operator",
      "/connect/some-secret-token",
      "/reset-password",
      "/verify-email",
    ];
    for (const path of blocked) {
      expect(isBlocked(rules, path), path).toBe(true);
    }
  });

  it("does not swallow a future public page that merely starts with a private prefix", () => {
    const { rules } = productionRobots();
    expect(isBlocked(rules, "/cases-studies")).toBe(false);
    expect(isBlocked(rules, "/billing-faq")).toBe(false);
    expect(isBlocked(rules, "/cases")).toBe(true);
    expect(isBlocked(rules, "/cases/123")).toBe(true);
  });

  it("emits a disallow pair per prefix", () => {
    expect(robotsDisallowRules()).toHaveLength(NOINDEX_PATH_PREFIXES.length * 2);
  });

  it.each([
    ["unset", undefined],
    ["the dev server or Docker build placeholder", "http://localhost:3000"],
    ["a bare IP", "https://13.62.74.24"],
    ["a tunnel", "https://x.ngrok-free.dev"],
  ])("blocks everything and publishes no sitemap when NEXTAUTH_URL is %s", (_label, url) => {
    vi.stubEnv("NEXTAUTH_URL", url ?? "");
    const result = robots();
    expect(result.rules).toEqual({ userAgent: "*", disallow: "/" });
    expect(result.sitemap).toBeUndefined();
  });
});

describe("sitemap.xml", () => {
  it("lists exactly the public, indexable pages on the production origin", () => {
    vi.stubEnv("NEXTAUTH_URL", PRODUCTION_ORIGIN);
    const urls = sitemap().map((entry) => entry.url);

    expect([...urls].sort()).toEqual(
      PUBLIC_PAGES.map((page) => (page.path === "/" ? PRODUCTION_ORIGIN : `${PRODUCTION_ORIGIN}${page.path}`)).sort(),
    );
    // The same string Next renders in the home page's <link rel="canonical">.
    expect(urls).toContain(PRODUCTION_ORIGIN);
    expect(urls).toContain(`${PRODUCTION_ORIGIN}/pricing`);
    expect(urls).toContain(`${PRODUCTION_ORIGIN}/docs/integrations/zendesk`);
  });

  it("has no duplicates, no query strings or fragments, and a single host", () => {
    vi.stubEnv("NEXTAUTH_URL", PRODUCTION_ORIGIN);
    const urls = sitemap().map((entry) => entry.url);
    expect(new Set(urls).size).toBe(urls.length);
    for (const url of urls) {
      const parsed = new URL(url);
      expect(parsed.origin, url).toBe(PRODUCTION_ORIGIN);
      expect(parsed.search, url).toBe("");
      expect(parsed.hash, url).toBe("");
      expect(url, url).not.toMatch(/localhost|127\.0\.0\.1/);
    }
  });

  it("excludes every authenticated, admin, API, token and non-indexable URL", () => {
    vi.stubEnv("NEXTAUTH_URL", PRODUCTION_ORIGIN);
    const paths = sitemap().map((entry) => new URL(entry.url).pathname);
    for (const path of paths) {
      expect(classifyPath(path), path).toBe("public-indexable");
    }
    for (const excluded of ["/sign-in", "/sign-up", "/dashboard", "/admin", "/api/health", "/docs/deployment", "/onboarding"]) {
      expect(paths).not.toContain(excluded);
    }
  });

  it("claims no modification dates, change frequencies or priorities it cannot know", () => {
    vi.stubEnv("NEXTAUTH_URL", PRODUCTION_ORIGIN);
    for (const entry of sitemap()) {
      expect(Object.keys(entry)).toEqual(["url"]);
    }
  });

  it.each([["http://localhost:3000"], ["https://13.62.74.24"], [""]])(
    "is empty when NEXTAUTH_URL is %s",
    (url) => {
      vi.stubEnv("NEXTAUTH_URL", url);
      expect(sitemap()).toEqual([]);
    },
  );
});

// ── The auth proxy must not stand between a crawler and its files ──────────

describe("proxy matcher", async () => {
  const { config } = await import("../src/proxy");
  const pattern = new RegExp(`^${config.matcher[0]}$`);

  it.each([
    "/robots.txt",
    "/sitemap.xml",
    "/manifest.webmanifest",
    "/favicon.ico",
    "/icon.png",
    "/apple-icon.png",
    "/icon-512.png",
    "/og-image.png",
    "/logo.svg",
    "/_next/static/chunks/main.js",
    "/_next/image",
  ])("lets %s through untouched", (path) => {
    expect(pattern.test(path), path).toBe(false);
  });

  it.each(["/", "/pricing", "/docs/cases", "/dashboard", "/sign-in", "/api/me", "/api/health", "/cases/export"])(
    "still runs the proxy for %s",
    (path) => {
      expect(pattern.test(path), path).toBe(true);
    },
  );

  it("exempts every generated asset route", () => {
    for (const path of ASSET_ROUTES) expect(pattern.test(path), path).toBe(false);
  });
});
