import { NextResponse } from "next/server";
import {
  extractZendeskWebhookTicketId,
  isZendeskWebhookTimestampFresh,
  runZendeskWebhookIngest,
  ZendeskApiError,
  ZendeskPermissionDeniedError,
  ZendeskReauthRequiredError,
} from "@sla/zendesk";
import { getPrismaClient, withOrganizationSlaLock } from "@sla/db";
import { normalizeAndProject, type IntegrationRef } from "@sla/ingestion";
import { PROVIDERS, WEB_PROVIDERS } from "@/lib/providers";
import { getZendeskOAuthConfig } from "@/lib/zendesk-env";
import { computeWebhookPipeline, deliverWebhookNotifications } from "@/lib/webhook-pipeline";

export const maxDuration = 60;

/**
 * Zendesk webhook receiver (roadmap step 20). Unauthenticated by session —
 * Zendesk calls this directly — so authenticity rests on a shared secret.
 * Zendesk's own webhook signing secret isn't usable here: it's generated by
 * Zendesk only after the webhook is created, with no field in the creation
 * form to hand it one of our own choosing. What the creation form's
 * Authentication dropdown does offer is "Bearer token", so customers paste
 * this integration's secret there and Zendesk sends it back as
 * `Authorization: Bearer <token>` on every call.
 *
 * On success this runs the full poll-cycle tail (ingest → normalize →
 * commitments → evaluation → notifications) for one ticket, synchronously,
 * which is what actually delivers "real-time freshness" — the 5-minute
 * active-set poll and 60-minute reconciliation sweep (roadmap step 7) keep
 * running unchanged as the safety net for missed or out-of-order deliveries.
 * Normalization and the pipeline tail run under `withOrganizationSlaLock`
 * (E-3): a concurrent worker cycle or another webhook for the same
 * organization waits rather than racing on the same Case/NormalizedEvent/
 * Commitment rows. Ingest itself is excluded — network-bound and
 * idempotent, so it never needs to wait.
 */
export async function POST(request: Request, { params }: { params: Promise<{ integrationId: string }> }) {
  const { integrationId } = await params;
  const prisma = getPrismaClient();

  const integration = await prisma.integration.findUnique({ where: { id: integrationId } });
  if (!integration || integration.provider !== "zendesk" || !integration.webhookSecret) {
    return NextResponse.json({ error: "Unknown webhook endpoint" }, { status: 404 });
  }

  if (!(await WEB_PROVIDERS.zendesk.verifyWebhook!(request.clone(), integration.webhookSecret))) {
    return NextResponse.json({ error: "Invalid webhook credentials" }, { status: 401 });
  }

  // A disconnected integration has no credentials to ingest with — accept
  // the delivery (so the customer's Zendesk instance doesn't see it as
  // failing and retry forever) but do nothing with it.
  if (integration.status === "disconnected") {
    return NextResponse.json({ status: "ignored", reason: "integration disconnected" });
  }

  let payload: unknown;
  try {
    payload = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  if (!isZendeskWebhookTimestampFresh(payload)) {
    return NextResponse.json({
        error:
          'Webhook timestamp missing, not ISO-8601, or expired: the trigger body needs "timestamp": "{{ticket.updated_at_with_timestamp}}"',
      }, { status: 401 });
  }

  const ticketId = extractZendeskWebhookTicketId(payload);
  if (ticketId === null) {
    return NextResponse.json({ error: "No ticket id found in webhook payload" }, { status: 400 });
  }

  let config;
  try {
    config = await getZendeskOAuthConfig(integration.organizationId);
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Zendesk OAuth is not configured" },
      { status: 500 },
    );
  }

  try {
    const ingest = await runZendeskWebhookIngest(prisma, integration.id, config, ticketId);

    await prisma.integration.update({
      where: { id: integration.id },
      data: { lastSyncAt: new Date(), lastSyncError: null },
    });
    // Access is evidently back — same compare-and-set self-clearing rule as
    // the worker cycle (a no-op unless the row is still `permission_denied`).
    await prisma.integration.updateMany({
      where: { id: integration.id, status: "permission_denied" },
      data: { status: "connected" },
    });

    const integrationRef: IntegrationRef = {
      id: integration.id,
      organizationId: integration.organizationId,
      provider: integration.provider,
      status: integration.status,
    };
    const normalizeTicket = () =>
      normalizeAndProject(PROVIDERS.zendesk, { prisma, integration: integrationRef, mode: "full", externalIds: [String(ticketId)] });

    // The ticket is gone: ingest recorded the deletion, and normalizing it
    // soft-deletes its Case. There's nothing new to derive, and the pipeline
    // tail would only re-evaluate commitments that the now-excluded case no
    // longer contributes to.
    if (ingest.ticketDeleted) {
      await withOrganizationSlaLock(prisma, integration.organizationId, normalizeTicket);
      return NextResponse.json({ status: "deleted", ticketId });
    }

    const { result, claims } = await withOrganizationSlaLock(prisma, integration.organizationId, async () => {
      await normalizeTicket();
      // Only this ticket's case: the lock is held for one ticket's worth of
      // work, not the organization's.
      const cases = await prisma.case.findMany({
        where: { organizationId: integration.organizationId, externalId: String(ticketId) },
        select: { id: true },
      });
      return computeWebhookPipeline(prisma, integration.organizationId, { caseIds: cases.map((c) => c.id) });
    });
    // Alerts go out after the lock is released (their claim rows were inserted inside it).
    const pipeline = await deliverWebhookNotifications(prisma, result, claims);

    return NextResponse.json({ status: "processed", ticketId, ...pipeline });
  } catch (error) {
    // A ticket the incremental export listed but that 404s on direct fetch
    // (merged away, permanently deleted) is a normal occurrence, not a
    // failure to retry — mirrors runZendeskBackfill's own handling.
    if (error instanceof ZendeskApiError && error.status === 404) {
      return NextResponse.json({ status: "ignored", reason: "ticket not found" });
    }

    if (error instanceof ZendeskReauthRequiredError) {
      await prisma.integration.update({
        where: { id: integration.id },
        data: { status: "reauth_required", lastSyncAt: new Date(), lastSyncError: "Zendesk needs to be reconnected" },
      });
      // Accepted, not retried: reconnecting requires a human, which no
      // number of Zendesk retries will produce.
      return NextResponse.json({ status: "ignored", reason: "reauth required" });
    }

    if (error instanceof ZendeskPermissionDeniedError) {
      await prisma.integration.update({
        where: { id: integration.id },
        data: {
          lastSyncAt: new Date(),
          lastSyncError: "Zendesk denied access — the connecting user's Zendesk permissions may have changed",
        },
      });
      // Compare-and-set, like the worker cycle: never overwrites a concurrent disconnect/reauth.
      await prisma.integration.updateMany({
        where: { id: integration.id, status: "connected" },
        data: { status: "permission_denied" },
      });
      // Accepted, not retried: restoring the user's access is a human step.
      // The next clean worker cycle clears the status on its own.
      return NextResponse.json({ status: "ignored", reason: "permission denied" });
    }

    const message = error instanceof Error ? error.message : String(error);
    await prisma.integration.update({
      where: { id: integration.id },
      data: { lastSyncAt: new Date(), lastSyncError: message },
    });
    return NextResponse.json({ error: message }, { status: 502 });
  }
}
